name: Apply BigQuery Permissions

on:
  push:
    branches:
      - master
    paths:
      - 'permissions/**.json'

jobs:
  permissions:
    name: Apply Permissions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          DIFF_FILTER: 'AMR'
          PATTERNS: |
            permissions/**.json
      - name: Run bq-permissions
        run: |
          echo Running bq-permissions on ${{ env.GIT_DIFF }}

